[package]
name = "day-21"
version = "0.1.0"
edition = "2021"

[dependencies]
z3 = "0.12.1"
z3-sys = "0.8.1"

[dev-dependencies]
divan = "^0.1"
mry = "^0.10"
gag = "^1.0"

[features]
part2 = []
full_bench = []
debug = []

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false