[package]
name = "day-14"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "^7.1.3"
bevy = "0.15"

[dev-dependencies]
divan = "^0.1"
mry = "^0.10"
gag = "^1.0"

[features]
sample = []
part2 = []
full_bench = []

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false