[package]
name = "day-23"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "^0.6"
itertools = "^0.13"

[dev-dependencies]
divan = "^0.1"
mry = "^0.10"
gag = "^1.0"

[features]
part2 = []
full_bench = []

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false