[package]
name = "day-17"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.54"
nom = "^7.1"

[dev-dependencies]
divan = "^0.1"
mry = "^0.10"
gag = "^1.0"

[features]
part2 = []
full_bench = []

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false